# values.yaml

replicaCount: 1

image:
  repository: arielk2511/star_meme_sql_compose
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

database:
  image: mysql:5.7
  replicaCount: 1
  service:
    name: mysql
    port: 3306
  auth:
    rootPassword: "rootpassword"  # Override using secrets
    database: stargifs

config:
  DB_HOST: "mysql"
  DB_USER: "root"
  DB_NAME: "stargifs"
  FLASK_PORT: "5000"

secrets:
  DB_PASSWORD: "cm9vdF9wYXNzd29yZA=="  # base64 encoded "rootpassword"

initSQL: |
  -- Create the database if it doesn't exist
  CREATE DATABASE IF NOT EXISTS stargifs;

  -- Use the created database
  USE stargifs;

  CREATE TABLE IF NOT EXISTS visitor_counter (
      id INT AUTO_INCREMENT PRIMARY KEY,
      count INT NOT NULL DEFAULT 0
  );

  -- Initialize the counter with a value
  INSERT INTO visitor_counter (count) VALUES (0);

  -- Create the 'images' table if it doesn't exist
  CREATE TABLE IF NOT EXISTS images (
      id INT AUTO_INCREMENT PRIMARY KEY,
      url VARCHAR(2000) NOT NULL
  );

  -- Insert some sample cat GIF URLs into the 'images' table
  INSERT INTO images (url) VALUES
  ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWhVVkX-ECkWuITbkKbOBzEayBLLXwLgqCZQ&s"),
  ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH8RnFlf6AbwIUCD9p03vWkrIXpQn1Hpc8Pw&s"),
  ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTunuv7Ntr7YxZKE8_mZFgV2-lsVnJZ4-Cb8g&s"),
  ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiElvS_DJZ5uxm9OqkhsefGEpEVi5cHoelaA&s"),
  ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfcjZ3c6XBJsZsAuQgogcuQAJmBvLIICxm-Q&s");
